### ISSUE TITLE
Boooo....

### ISSUE THREAD

**Issue by msfjarvis** [faddat/jacobgadikian.com#1]
Is the site down, @faddat ??? Or is it that you haven't gotten around to pushing it online ???

**Comment by faddat** [comment]
I guess you could say it's some of column A and some of column B.  Keeping
Klouds.org moving takes up a great deal of my time.....

Jacob Gadikian
E-mail: faddat@gmail.com
SKYPE: faddat
Phone/SMS: +84 167 789 6421

**Comment by msfjarvis** [comment]
Trust me, your effort shows in klouds.org so i'm gonna be closing this issue
